name: test_project
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.2
  flutter_bloc: ^8.1.3
  json_annotation: ^4.7.0
  dio: ^5.2.1+1
  get_it: ^7.6.0
  keyboard_dismisser: ^3.0.0
  connectivity_plus: ^4.0.1
  freezed_annotation: ^2.4.1
  path_provider: ^2.0.15
  intl: ^0.18.0
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.5.4
  build_runner: ^2.3.3
  freezed: ^2.4.1

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Black.ttf
  #         weight: 900
  #       - asset: assets/fonts/Roboto-BlackItalic.ttf
  #         weight: 900
  #         style: italic
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 800
  #       - asset: assets/fonts/Roboto-BoldItalic.ttf
  #         weight: 800
  #         style: italic
  #       - asset: assets/fonts/Roboto-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-MediumItalic.ttf
  #         weight: 500
  #         style: italic
  #       - asset: assets/fonts/Roboto-LightItalic.ttf
  #         weight: 300
  #         style: italic
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Roboto-Thin.ttf
  #         weight: 100
